name: 'PR Commenter'
description: 'Adds a comment to a PR that can differ depending on which files are being changed in that PR.'
author: exercism
inputs:
  github-token:
    description: 'Auth token used to manage issues or pull requests'
    default: ${{ github.token }}
    required: false
  config-file:
    description: 'The path to the action configuration file'
    default: '.github/pr-commenter.yml'
    required: false
  template-variables:
    description: 'A string with a JSON that holds variables that will be used when rendering the Mustache templates'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'message-circle'
  color: 'purple'
